In [1]:
import numpy as np
import math

In [47]:
M = np.matrix([
    [2,1,1,10],
    [3,2,3,18],
    [1,4,9,16]
])

In [48]:
eq4 = 3*M[0,:] - M[1,:]
print(eq4)

[[ 3  1  0 12]]


In [49]:
M = np.append(M,eq4,axis=0)
print(M)

[[ 2  1  1 10]
 [ 3  2  3 18]
 [ 1  4  9 16]
 [ 3  1  0 12]]


In [50]:
eq5 = 9*M[0,:] - M[2,:]
print(eq5)

[[17  5  0 74]]


In [51]:
M = np.append(M,eq5,axis=0)
print(M)

[[ 2  1  1 10]
 [ 3  2  3 18]
 [ 1  4  9 16]
 [ 3  1  0 12]
 [17  5  0 74]]


In [52]:
eq6 = M[4:,] - 5*M[3,:]
eq6 = eq6/2
print(eq6)

[[1. 0. 0. 7.]]


In [53]:
M = np.append(M,eq6,axis=0)
print(M)

[[ 2.  1.  1. 10.]
 [ 3.  2.  3. 18.]
 [ 1.  4.  9. 16.]
 [ 3.  1.  0. 12.]
 [17.  5.  0. 74.]
 [ 1.  0.  0.  7.]]


In [54]:
eq7 = eq4 -eq6
print(eq7)

[[2. 1. 0. 5.]]


In [55]:
eq7 = M[3,:] - 3*M[5,:]
print(eq7)

[[ 0.  1.  0. -9.]]


In [56]:
M = np.append(M,eq7,axis=0)
print(M)

[[ 2.  1.  1. 10.]
 [ 3.  2.  3. 18.]
 [ 1.  4.  9. 16.]
 [ 3.  1.  0. 12.]
 [17.  5.  0. 74.]
 [ 1.  0.  0.  7.]
 [ 0.  1.  0. -9.]]


In [57]:
eq8 = M[0,:] - 2*M[5,:] - M[6,:]
print(eq8)

[[0. 0. 1. 5.]]


In [58]:
M = np.append(M,eq8,axis=0)
print(M)

[[ 2.  1.  1. 10.]
 [ 3.  2.  3. 18.]
 [ 1.  4.  9. 16.]
 [ 3.  1.  0. 12.]
 [17.  5.  0. 74.]
 [ 1.  0.  0.  7.]
 [ 0.  1.  0. -9.]
 [ 0.  0.  1.  5.]]


## Task2

In [26]:
A = np.matrix([
    [2.0,1.0,1.0],
    [3.0,2.0,3.0],
    [1.0,4.0,9.0]
])

b = np.matrix([
    [10.0],
    [18.0],
    [16.0]
])

In [27]:
# x = inverse(a)*b

inverseA = np.linalg.inv(A)

In [28]:
x = np.dot(inverseA,b)

In [29]:
x

matrix([[ 7.],
        [-9.],
        [ 5.]])

## Task3 

In [30]:
a = np.matrix([
    [2.0 , -5.0],
    [3.0 , 1.0]
])
b = np.matrix([
    [15.0],
    [31.0]
])
c = np.matrix([
    [2.0,1.0,1.0],
    [3.0,2.0,3.0],
    [1.0,4.0,9.0]
])

d = np.matrix([
    [10.0],
    [18.0],
    [16.0]
])
    
m = np.matrix([
    [1.0, 2.0 , 1.0 , 4.0],
    [2.0 , 0 , 4.0 , 3.0],
    [4.0 , 2.0 , 2.0 , 1.0],
    [-3.0 , 1.0 , 3.0 , 2.0]
])
l = np.matrix([[13.0],[28.0],[20.0],[6.0]])

In [31]:
ab = np.append(a,b,axis=1)
cd = np.append(c,d,axis=1)
ml = np.append(m,l,axis=1)

In [32]:
def fwd_elim(Ab):
    Abx = Ab.copy()
    [nr,nc] = Abx.shape
    
    for i in range(1,nr):
        
        for r in range(i,nr):
            print('Iteration #{}  index = {}'.format(i,r))
            row_factor = Abx[r,i-1]/Abx[i-1,i-1]
            Abx[r,:] = Abx[r,:] - Abx[i-1,:]*row_factor
        #end for r
    #end for i
    print(Abx)
    return Abx
#end fuction

In [33]:
def back_sub(Ab):
    Abx = Ab.copy()
    [nr,nc] = Abx.shape
    
    x = np.empty(nr)
    for r in range(nr-1,-1,-1):
        print('r = {}'.format(r))
        sum_of_product = 0
        for i in range(r+1,nr):
            print('i = {}'.format(i))
            product = Abx[r,i]*x[i]
            sum_of_product = sum_of_product + product
        #end for
        x[r] = (Abx[r,nc-1] - sum_of_product)/Abx[r,r]
    
    #end for
    print(x)
    return x
#end fuction
    

In [34]:
ab_re = fwd_elim(ab)
print(ab_re)

Iteration #1  index = 1
[[ 2.  -5.  15. ]
 [ 0.   8.5  8.5]]
[[ 2.  -5.  15. ]
 [ 0.   8.5  8.5]]


In [35]:
back_sub(ab_re)

r = 1
r = 0
i = 1
[10.  1.]


array([10.,  1.])

In [36]:
cd_re = fwd_elim(cd)
print(cd_re)

Iteration #1  index = 1
Iteration #1  index = 2
Iteration #2  index = 2
[[  2.    1.    1.   10. ]
 [  0.    0.5   1.5   3. ]
 [  0.    0.   -2.  -10. ]]
[[  2.    1.    1.   10. ]
 [  0.    0.5   1.5   3. ]
 [  0.    0.   -2.  -10. ]]


In [37]:
back_sub(cd_re)

r = 2
r = 1
i = 2
r = 0
i = 1
i = 2
[ 7. -9.  5.]


array([ 7., -9.,  5.])

In [38]:
ml_re = fwd_elim(ml)
print(ml_re)

Iteration #1  index = 1
Iteration #1  index = 2
Iteration #1  index = 3
Iteration #2  index = 2
Iteration #2  index = 3
Iteration #3  index = 3
[[  1.    2.    1.    4.   13. ]
 [  0.   -4.    2.   -5.    2. ]
 [  0.    0.   -5.   -7.5 -35. ]
 [  0.    0.    0.   -9.  -18. ]]
[[  1.    2.    1.    4.   13. ]
 [  0.   -4.    2.   -5.    2. ]
 [  0.    0.   -5.   -7.5 -35. ]
 [  0.    0.    0.   -9.  -18. ]]


In [39]:
back_sub(ml_re)

r = 3
r = 2
i = 3
r = 1
i = 2
i = 3
r = 0
i = 1
i = 2
i = 3
[ 3. -1.  4.  2.]


array([ 3., -1.,  4.,  2.])

## Task4

In [40]:
a = np.matrix([
    [2.0 , -5.0],
    [3.0 , 1.0]
])
b = np.matrix([
    [15.0],
    [31.0]
])
c = np.matrix([
    [2.0,1.0,1.0],
    [3.0,2.0,3.0],
    [1.0,4.0,9.0]
])

d = np.matrix([
    [10.0],
    [18.0],
    [16.0]
])
    
m = np.matrix([
    [1.0, 2.0 , 1.0 , 4.0],
    [2.0 , 0 , 4.0 , 3.0],
    [4.0 , 2.0 , 2.0 , 1.0],
    [-3.0 , 1.0 , 3.0 , 2.0]
])
l = np.matrix([
    [13.0],
    [28.0],
    [20.0],
    [6.0]
])

In [41]:
def Cramerrule(A,B):
    size = A.shape
    ans = np.empty(size[0])
    for i in range(size[0]):
        ax = A.copy()
        ax[:,i] = B
        ans[i] = np.linalg.det(ax)/np.linalg.det(A)
    print(ans)

In [42]:
Cramerrule(a,b)

[10.  1.]


In [43]:
Cramerrule(c,d)

[ 7. -9.  5.]


In [44]:
Cramerrule(m,l)

[ 3. -1.  4.  2.]


## Task5

In [70]:
A = np.array([
    [0,2,5],
    [2,1,1],
    [3,1,0]
])
A = A*1.0
b = np.array([
    [1],
    [1],
    [2]
])
b = b*1.0

In [71]:
Ab = np.append(A,b , axis = 1)
print(Ab)

[[0. 2. 5. 1.]
 [2. 1. 1. 1.]
 [3. 1. 0. 2.]]


In [72]:
Ab

array([[0., 2., 5., 1.],
       [2., 1., 1., 1.],
       [3., 1., 0., 2.]])

In [73]:
## swap row 3 and row 1
temp = Ab[0,:].copy()
Ab[0,:] = Ab[2,:].copy()
Ab[2,:] = temp
print(Ab)

[[3. 1. 0. 2.]
 [2. 1. 1. 1.]
 [0. 2. 5. 1.]]


In [74]:
Ab_re = fwd_elim(Ab)
print(Ab_re)

Iteration #1  index = 1
Iteration #1  index = 2
Iteration #2  index = 2
[[ 3.          1.          0.          2.        ]
 [ 0.          0.33333333  1.         -0.33333333]
 [ 0.          0.         -1.          3.        ]]
[[ 3.          1.          0.          2.        ]
 [ 0.          0.33333333  1.         -0.33333333]
 [ 0.          0.         -1.          3.        ]]


In [75]:
x = back_sub(Ab_re)
print(x)

r = 2
r = 1
i = 2
r = 0
i = 1
i = 2
[-2.  8. -3.]
[-2.  8. -3.]
