In [313]:
import numpy as np
import math


In [314]:
a = np.matrix([
    [2,1,1],
    [3,2,3],
    [1,4,9]
])

b = np.matrix([
    [10],
    [18],
    [16]
])

In [315]:
print(a)

[[2 1 1]
 [3 2 3]
 [1 4 9]]


In [316]:
print(b)

[[10]
 [18]
 [16]]


In [317]:
a = np.matrix([
    [4,-2,1],
    [1,1,1],
    [9,3,1]
])

b = np.matrix([
    [8],
    [-13],
    [3]
])

In [318]:
print(a)

[[ 4 -2  1]
 [ 1  1  1]
 [ 9  3  1]]


In [319]:
print(b)

[[  8]
 [-13]
 [  3]]


In [320]:
ab = np.append(a,b,axis=1)

In [321]:
print(ab)

[[  4  -2   1   8]
 [  1   1   1 -13]
 [  9   3   1   3]]


In [322]:
ab[1,:]

matrix([[  1,   1,   1, -13]])

In [323]:
ab[0,:]

matrix([[ 4, -2,  1,  8]])

In [324]:
ab[0,1:2]

matrix([[-2]])

In [325]:
ab[0,1:3]

matrix([[-2,  1]])

In [326]:
ab[0,:]

matrix([[ 4, -2,  1,  8]])

In [327]:
ab[1,:]

matrix([[  1,   1,   1, -13]])

In [328]:
ab[1,:] = ab[0,:] - ab[1,:]

In [329]:
ab

matrix([[ 4, -2,  1,  8],
        [ 3, -3,  0, 21],
        [ 9,  3,  1,  3]])

In [330]:
ab[1,:] = ab[1,:]/3

In [331]:
ab

matrix([[ 4, -2,  1,  8],
        [ 1, -1,  0,  7],
        [ 9,  3,  1,  3]])

In [332]:
ab[2,:] = ab[2,:] - ab[0,:]

In [333]:
ab

matrix([[ 4, -2,  1,  8],
        [ 1, -1,  0,  7],
        [ 5,  5,  0, -5]])

In [334]:
ab[2,:] = ab[2,:]/5

In [335]:
ab

matrix([[ 4, -2,  1,  8],
        [ 1, -1,  0,  7],
        [ 1,  1,  0, -1]])

In [336]:
ab[2,:] = ab[2,:]+ab[1,:]

In [337]:
ab

matrix([[ 4, -2,  1,  8],
        [ 1, -1,  0,  7],
        [ 2,  0,  0,  6]])

In [338]:
ab[2,:] = ab[2,:]/2

In [339]:
ab

matrix([[ 4, -2,  1,  8],
        [ 1, -1,  0,  7],
        [ 1,  0,  0,  3]])

In [340]:
ab[1,:] = ab[2,:]- ab[1,:]
ab

matrix([[ 4, -2,  1,  8],
        [ 0,  1,  0, -4],
        [ 1,  0,  0,  3]])

In [341]:
ab[0,:] = ab[0,:] - 4*ab[2,:] + 2*ab[1,:]
ab

matrix([[  0,   0,   1, -12],
        [  0,   1,   0,  -4],
        [  1,   0,   0,   3]])

In [342]:
ab = np.matrix([[  0,   0,   1, -12],
        [  0,   1,   0,  -4],
        [  1,   0,   0,   3]])
ab

matrix([[  0,   0,   1, -12],
        [  0,   1,   0,  -4],
        [  1,   0,   0,   3]])

In [343]:
temp = ab[2,:].copy()
ab[2,:] = ab[0,:]
ab[0,:] = temp
ab


matrix([[  1,   0,   0,   3],
        [  0,   1,   0,  -4],
        [  0,   0,   1, -12]])

# Method2

In [344]:
a = np.matrix([
    [4,-2,1],
    [1,1,1],
    [9,3,1]
])

b = np.matrix([
    [8],
    [-13],
    [3]
])

In [345]:
a

matrix([[ 4, -2,  1],
        [ 1,  1,  1],
        [ 9,  3,  1]])

In [346]:
b

matrix([[  8],
        [-13],
        [  3]])

In [347]:
# x = invverse(a) * b

inv_a = np.linalg.inv(a)

In [348]:
inv_a

matrix([[ 0.06666667, -0.16666667,  0.1       ],
        [-0.26666667,  0.16666667,  0.1       ],
        [ 0.2       ,  1.        , -0.2       ]])

In [349]:
t1 = np.dot(a,inv_a)
print(t1)

[[ 1.00000000e+00  0.00000000e+00 -5.55111512e-17]
 [ 2.77555756e-17  1.00000000e+00  0.00000000e+00]
 [-2.77555756e-17  0.00000000e+00  1.00000000e+00]]


In [350]:
t2 = np.dot(inv_a,a)
print(t2)

[[ 1.00000000e+00 -1.38777878e-17  0.00000000e+00]
 [ 1.38777878e-16  1.00000000e+00  2.77555756e-17]
 [ 1.66533454e-16 -1.66533454e-16  1.00000000e+00]]


In [351]:
x = np.dot(inv_a,b)
x

matrix([[  3.],
        [ -4.],
        [-12.]])

# Method 4

In [352]:
a

matrix([[ 4, -2,  1],
        [ 1,  1,  1],
        [ 9,  3,  1]])

In [353]:
ax1 = a.copy()
ax1

matrix([[ 4, -2,  1],
        [ 1,  1,  1],
        [ 9,  3,  1]])

In [354]:
ax1[:,0] = b
ax1

matrix([[  8,  -2,   1],
        [-13,   1,   1],
        [  3,   3,   1]])

In [355]:
x1 = np.linalg.det(ax1)/np.linalg.det(a)
print(x1)

2.9999999999999996


In [356]:
ax2 = a.copy()
ax2[:,1] = b
x2 = np.linalg.det(ax2)/np.linalg.det(a)
x2

-4.000000000000003

In [357]:
ax3 = a.copy()
ax3[:,1] = b
x3 = np.linalg.det(ax3)/np.linalg.det(a)
x3


-4.000000000000003

# Method 3

In [358]:
a = np.matrix([
    [4.0,-2.0,1.0],
    [1.0,1.0,1.0],
    [9.0,3.0,1.0]
])

b = np.matrix([
    [8.0],
    [-13.0],
    [3.0]
])

In [359]:
ab = np.append(a,b,axis=1)

In [360]:
ab

matrix([[  4.,  -2.,   1.,   8.],
        [  1.,   1.,   1., -13.],
        [  9.,   3.,   1.,   3.]])

In [361]:
def fwd_elim(ab):
    abx = ab.copy()
    [nr,nc] = ab.shape
    
    #Step1 : eliminate the front terms of row 2 to N
    for r in range(1,nr):
        row_factor = abx[r,0]/abx[0,0]
        abx[r,:] = ab[r,:] - (abx[0,:]* row_factor)
    #end for
    
    #Step2 : eliminate the 2nd terms off row  2 to N
    for r in range(2,nr):
        row_factor = abx[r,1]/abx[1,1]
        abx[r,:] = abx[r,:] - (abx[1,:]*row_factor)
        
    print(abx)
    return abx
#end function

In [362]:
fwd_elim(ab)

[[  4.    -2.     1.     8.  ]
 [  0.     1.5    0.75 -15.  ]
 [  0.     0.    -5.    60.  ]]


matrix([[  4.  ,  -2.  ,   1.  ,   8.  ],
        [  0.  ,   1.5 ,   0.75, -15.  ],
        [  0.  ,   0.  ,  -5.  ,  60.  ]])

In [363]:
def back_sub_v1(ab_re):
    abx = ab_re.copy()
    [nr,nc] = abx.shape
    
    x= np.zeros(3)
    
    #step 1:find x[2]:
    x[2] = abx[nr-1 , nc-1]/abx[nr-1,nc-2]
    print(x[2])
    
#end function

In [364]:
ab

matrix([[  4.,  -2.,   1.,   8.],
        [  1.,   1.,   1., -13.],
        [  9.,   3.,   1.,   3.]])

In [365]:
ab_re = fwd_elim(ab)

[[  4.    -2.     1.     8.  ]
 [  0.     1.5    0.75 -15.  ]
 [  0.     0.    -5.    60.  ]]


In [366]:
ab_re

matrix([[  4.  ,  -2.  ,   1.  ,   8.  ],
        [  0.  ,   1.5 ,   0.75, -15.  ],
        [  0.  ,   0.  ,  -5.  ,  60.  ]])

In [367]:
back_sub_v1(ab_re)

-12.0


In [368]:
def back_sub_v2(ab_re):
    abx = ab_re.copy()
    [nr,nc] = abx.shape
    
    x= np.zeros(3)
    
    #step 1:find x[2]:
    x[2] = abx[nr-1 , nc-1]/abx[nr-1,nc-2]
    print(x[2])
    
    #step 2: find x[1]:
    x[1] = abx[nr-2, nc-1] - abx[nr-2,nc-2]*x[2]/abx[nr-2 , nc-3]
    print(x[1])
    
#end function

In [369]:
def back_sub_v3(ab_re):
    abx = ab_re.copy()
    [nr,nc] = abx.shape
    
    x= np.zeros(3)
    
    #step 1:find x[2]:
    x[2] = abx[nr-1 , nc-1]/abx[nr-1,nc-2]
    print(x[2])
    
    #step 2: find x[1]:
    x[1] = abx[nr-2, nc-1] - abx[nr-2,nc-2]*x[2]/abx[nr-2 , nc-3]
    print(x[1])
    
    #step 3 : fix x[0]:
    x[0] = abx[nr-3,nc-1]  - abx[nr-3,nc-2]*x[2]/abx[nr-3,nc-3]*x[1]/abx[nr-3,nc-4]
    print(x[0])
#end function

In [370]:
back_sub_v3(ab_re)

-12.0
-9.0
21.5
